version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: gitgoose
      POSTGRES_PASSWORD: gitgoose
      POSTGRES_DB: gitgoose
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "3003:3000"
    depends_on:
      - prometheus
    restart: always

  gitgoose-nest:
    build:
      context: ./gitgoose-nest
      dockerfile: Dockerfile
    env_file:
      - ./gitgoose-nest/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - gitgoose-nest-git
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  gitgoose-nest-git:
    build:
      context: ./gitgoose-nest-git
      dockerfile: Dockerfile
    env_file:
      - ./gitgoose-nest-git/.env.docker
    volumes:
      - git_storage:/git-storage
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

volumes:
  postgres_data:
  git_storage:
  prometheus_data:
  grafana_data:
