global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gitgoose-nest'
    static_configs:
      - targets: ['gitgoose-nest:3000']
    metrics_path: '/metrics'

  - job_name: 'gitgoose-nest-git'
    static_configs:
      - targets: ['gitgoose-nest-git:3001']
    metrics_path: '/metrics'